### PR TITLE
fix(electron): 💊 fix routing daemon installation issue in Linux

### LINKED ISSUE #1269: Linux client does not work for Ubuntu for the first time
**Describe the bug**
I am not able to connect to the VPN server the first time I run Outline client. After restarting the client, it works.

**To Reproduce**
1. Using a clean Ubuntu machine
2. Double click Outline-Client.AppImage
3. Type in the root password if prompted
4. Though the UI shows connected, actually it is not
5. You will not be able to disconnect as well
6. Not able to quit as well

**Expected behavior**
We should successfully connect to the VPN server.

**Screenshots**
image

**Client System (please complete the following information):**
 - Outline Client Version 1.4.0 and 1.7.0-dev
 - Your Operating System: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jyyi1**
In this PR, I fixed the routing daemon installation issue in Linux. Previously the logic was to launch `BadvpnTun2socks` first, and then tried to install daemon if it is not installed. This will cause failures because we did not relaunch `BadvpnTun2socks` after the installation. Now the new workflows are illustrated below.

#### Normal User Experience

https://user-images.githubusercontent.com/93548144/167020144-16273b08-9e0d-4029-b8f5-7b3731a89cee.mov

#### Edge Cases

https://user-images.githubusercontent.com/93548144/167020645-5d60e58e-1300-48ed-8161-e60479444f94.mov

Fixes #1269 .

Follow up task: update translations.

### CODE REVIEW

File: src/electron/routing_service.ts [hunk 1]
```diff
@@ -65,75 +63,79 @@ enum RoutingServiceStatusCode {
...
 
   private networkChangeListener?: (status: TunnelStatus) => void;
 
   constructor(private proxyAddress: string, private isAutoConnect: boolean) {}
 
+  /**
+   * Make sure the routing daemon is installed in the system.
+   * A SystemConfigurationException will be thrown if installation failed.
+   */
+  public async ensureDaemonInstalled() {
```
Comment (jyyi1) [inline src/electron/routing_service.ts:84]: This is the core part.

File: src/electron/go_vpn_tunnel.ts [hunk 2]
```diff
@@ -86,11 +86,13 @@ export class GoVpnTunnel implements VpnTunnel {
 
   // Fulfills once all three helpers have started successfully.
   async connect(checkProxyConnectivity: boolean) {
+    await this.routing.ensureDaemonInstalled();
```
Comment (jyyi1) [inline src/electron/go_vpn_tunnel.ts:89]: Just in case in the future we switch to go stack.

File: src/electron/sslibev_badvpn_tunnel.ts [hunk 3]
```diff
@@ -171,13 +177,15 @@ export class ShadowsocksLibevBadvpnTunnel implements VpnTunnel {
 
   // Fulfills once all three helpers have started successfully.
   async connect(checkProxyConnectivity: boolean) {
+    await this.routing.ensureDaemonInstalled();
```
Comment (jyyi1) [inline src/electron/sslibev_badvpn_tunnel.ts:180]: This is the key logic to fix the issue.

File: src/electron/routing_service.ts [hunk 4]
```diff
@@ -213,7 +216,30 @@ export class RoutingDaemon {
     return this.disconnected;
   }
 
-  public set onNetworkChange(newListener: ((status: TunnelStatus) => void)|undefined) {
+  public set onNetworkChange(newListener: ((status: TunnelStatus) => void) | undefined) {
     this.networkChangeListener = newListener;
   }
+
+  private isDaemonInstalled(): Promise<boolean> {
```
Comment (jyyi1) [inline src/electron/routing_service.ts:223]: Two helpers here.

File: src/electron/routing_service.ts [hunk 5]
```diff
@@ -213,7 +216,30 @@ export class RoutingDaemon {
...
+    return new Promise<boolean>(resolve => {
+      const connection: Socket = createConnection(SERVICE_NAME, () => connection.destroy());
+      connection.once("error", () => connection.destroy());
```
Comment (fortuna) [inline src/electron/routing_service.ts:226]: Is close still called on error or will the Promise be pending forever?

File: src/electron/routing_service.ts [hunk 6]
```diff
@@ -213,7 +216,30 @@ export class RoutingDaemon {
...
+      connection.once("close", hasError => resolve(!hasError));
+    });
+  }
+
+  private installDaemon(): Promise<void> {
+    console.info(`(re-)installing routing daemon`);
```
Comment (fortuna) [inline src/electron/routing_service.ts:232]: I'd simplify the text:
```suggestion
    console.info(`Installing routing daemon`);
```

File: src/electron/routing_service.ts [hunk 7]
```diff
@@ -65,75 +63,79 @@ enum RoutingServiceStatusCode {
...
+  /**
+   * Make sure the routing daemon is installed in the system.
+   * A SystemConfigurationException will be thrown if installation failed.
+   */
+  public async ensureDaemonInstalled() {
+    if (await this.isDaemonInstalled()) {
+      return;
+    }
+    if (isWindows) {
+      throw new errors.SystemConfigurationException("please rerun Outline installer in Windows");
```
Comment (fortuna) [inline src/electron/routing_service.ts:89]: We need to surface a localized message to the user, though this is not really the right place for UI.
Return an error that the UI can identify and display the right message to the user.

File: src/electron/routing_service.ts [hunk 8]
```diff
@@ -65,75 +63,79 @@ enum RoutingServiceStatusCode {
...
   private networkChangeListener?: (status: TunnelStatus) => void;
 
   constructor(private proxyAddress: string, private isAutoConnect: boolean) {}
 
+  /**
+   * Make sure the routing daemon is installed in the system.
+   * A SystemConfigurationException will be thrown if installation failed.
+   */
+  public async ensureDaemonInstalled() {
+    if (await this.isDaemonInstalled()) {
```
Comment (fortuna) [inline src/electron/routing_service.ts:85]: Let's tweak the design so that the layers are clean and we can properly do the UI.

This is my suggestion:
1. Make `VpnTunnel.connect` throw some "vpn not set up/configured"  error
1. Make the calling app code catch that and display the appropriate UI to the user:
  - On Windows, just tell them to rerun the installer.
  - On Linux
    1. use a dialog (it can be `window.confirm` for now, up to you) to tell the user that the vpn needs to be configured and needs permission.
    1. Trigger the installer with the permission prompt. The installer could be run by some `VpnTunnel.install/configure/setup()` method.
    1.  That setup can fail, in which case I guess we could suggest the user to reinstall the app or report feedback. We should at least output an install error.

Both the errors and dialogs need to use localized messages.

**Review by fortuna — CHANGES_REQUESTED** [review]
Thanks for the change. We need to tweak the code a bit because application logic is leaking into the lower level VpnTunnel abstraction.

File: src/electron/routing_service.ts (hunk 5 above)
Comment (jyyi1) [reply src/electron/routing_service.ts:226]: `destroy` will do the close thing.

File: src/electron/routing_service.ts (hunk 8 above)
Comment (jyyi1) [reply src/electron/routing_service.ts:85]: So to clarify this, are you suggesting let's handle the error in the very top UI layer instead of the `RoutingDaemon` or `VpnTunnel`? We can have a discussion offline.

**Comment by jyyi1** [comment]
To many re-formatting lines, do it in a separate PR.

**Review by jyyi1 — COMMENTED** [review]
Too many re-formatting lines, do it in a separate PR (#1298).

File: src/electron/routing_service.ts [hunk 9]
```diff
@@ -200,18 +179,21 @@ export class RoutingDaemon {
...
+      }
+      if (this.stopping) {
+        // Already stopped.
+        return;
+      }
+      this.stopping = true;
+
+      return this.writeReset();
+    } finally {
       this.fulfillDisconnect();
```
Comment (jyyi1) [inline src/electron/routing_service.ts:195]: This might not work, the `fulfillDisconnect` should be called in `cleanup`.

File: src/www/messages/en.json [hunk 10]
```diff
@@ -42,7 +42,7 @@
   "non-system-vpn-warning-detail": "Most browsers connect automatically with Outline, some do not.",
   "non-system-vpn-warning-title": "Verify your browser connection",
   "tray-open-window": "Open",
-  "outline-plugin-error-admin-permissions": "Outline needs admin permissions in order to run. If you don't have admin permissions, please try again after restarting your Windows computer or ask your system administrator for help.",
+  "outline-plugin-error-admin-permissions": "Outline needs admin permissions in order to run. If you don't have admin permissions, please try again after restarting your computer or ask your system administrator for help.",
```
Comment (fortuna) [inline src/www/messages/en.json:45]: Outline doesn't really need to ask for admin permissions to run. I think something like this would be more accurate:
```suggestion
  "outline-plugin-error-admin-permissions": "Outline needs admin permissions in order to set up the Outline VPN. If you don't have admin permissions, please try again after restarting your computer or ask your system administrator for help.",
```

File: src/www/messages/en.json [hunk 11]
```diff
@@ -51,6 +51,9 @@
   "outline-plugin-error-udp-forwarding-not-enabled": "It seems like this server doesn’t support UDP forwarding. If this happens again, please contact your server admin.",
   "outline-plugin-error-unsupported-routing-table": "It seems like another VPN is active. Please disconnect it and try again.",
   "outline-plugin-error-vpn-permission-not-granted": "Outline needs your permission to set up a VPN connection to the server. Please try again, or submit feedback if you need help.",
+  "outline-services-installation-confirmation": "We will install Outline Services to the operating system which may require admin permissions. Would you like to proceed?",
```
Comment (fortuna) [inline src/www/messages/en.json:54]: "Outline Services" doesn't really have a meaning to the user. Perhaps something like this:

```suggestion
  "outline-services-installation-confirmation": "We will set up the Outline VPN, which may require admin permissions. Would you like to proceed?",
```

File: src/www/messages/en.json [hunk 12]
```diff
@@ -51,6 +51,9 @@
...
+  "outline-services-installed": "Outline services have been successfully installed, please try again to connect to the server.",
```
Comment (fortuna) [inline src/www/messages/en.json:55]: Same:
```suggestion
  "outline-services-installed": "The Outline VPN has been successfully set up, please try again to connect to the server.",
```

File: src/www/app/electron_outline_tunnel.ts [hunk 13]
```diff
@@ -51,7 +55,12 @@ export class ElectronOutlineTunnel implements Tunnel {
       this.running = true;
     } catch (e) {
       if (typeof e === 'number') {
-        throw new errors.OutlinePluginError(e);
+        if (e === ErrorCode.SYSTEM_MISCONFIGURED) {
+          if (await this.tryInstallServices()) {
```
Comment (fortuna) [inline src/www/app/electron_outline_tunnel.ts:59]: Handle this error in the caller instead.

File: src/www/app/electron_outline_tunnel.ts [hunk 14]
```diff
@@ -87,4 +96,24 @@ export class ElectronOutlineTunnel implements Tunnel {
       console.error(`${this.id} status changed to ${status} but no listener set`);
     }
   }
+
+  private async tryInstallServices(): Promise<boolean> {
+    if (!isLinux) {
+      return Promise.resolve(false);
+    }
+    const confirmation = await this.uiService.showConfirmation('outline-services-installation-confirmation');
```
Comment (fortuna) [inline src/www/app/electron_outline_tunnel.ts:104]: UI does not belong here. Think of ElectronOutlineTunnel as part of an SDK that other apps may use.

Instead, propagate a system misconfigured error and handle it in the app code that is calling `start()`
You also need a method to set up the VPN that the app code can call.

File: src/www/app/electron_main.ts [hunk 15]
```diff
@@ -104,9 +104,9 @@ main({
   getNativeNetworking: () => {
     return isOsSupported ? new ElectronNativeNetworking() : new FakeNativeNetworking();
   },
-  getTunnelFactory: () => {
+  getTunnelFactory: uiService => {
     return (id: string) => {
-      return isOsSupported ? new ElectronOutlineTunnel(id) : new FakeOutlineTunnel(id);
+      return isOsSupported ? new ElectronOutlineTunnel(id, uiService) : new FakeOutlineTunnel(id);
```
Comment (fortuna) [inline src/www/app/electron_main.ts:109]: Revert. ElectronOutlineTunnel should be agnostic to the UI. See other comments.

File: src/www/app/ui_service.ts [hunk 16]
```diff
@@ -0,0 +1,74 @@
...
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+/**
+ * The UI component should realize this interface.
+ */
+export interface OutlineUIServiceHandler {
```
Comment (fortuna) [inline src/www/app/ui_service.ts:18]: The interface and class here are only needed to inject UI into the Electron tunnel. Let's revert this file.

File: src/www/model/errors.ts [hunk 17]
```diff
@@ -124,6 +126,8 @@ export const enum ErrorCode {
   NO_ADMIN_PERMISSIONS = 10,
   UNSUPPORTED_ROUTING_TABLE = 11,
   SYSTEM_MISCONFIGURED = 12,
+  // server connection failed, but successfully install the Outline services
+  SYSTEM_MISCONFIGURED_WITH_SUCCESSFUL_INSTALLATION = 13,
```
Comment (fortuna) [inline src/www/model/errors.ts:130]: I think this error is no longer needed, as the UI will be handling the error directly.

File: src/www/app/platform.ts [hunk 18]
```diff
@@ -31,7 +32,7 @@ export interface OutlinePlatform {
 
   getNativeNetworking(): NativeNetworking;
 
-  getTunnelFactory(): TunnelFactory;
+  getTunnelFactory(uiService: OutlineUIService): TunnelFactory;
```
Comment (fortuna) [inline src/www/app/platform.ts:35]: Revert

File: src/www/app/main.ts [hunk 19]
```diff
@@ -96,12 +97,13 @@ export function main(platform: OutlinePlatform) {
       const debugMode = queryParams.get('debug') === 'true';
 
       const eventQueue = new EventQueue();
+      const uiService = new OutlineUIService();
```
Comment (fortuna) [inline src/www/app/main.ts:100]: Revert.
Handle the system not configured before you call start() (by checking the set up status) or by handling a not set configured error thrown by start().
You then call a method to configure/set up the VPN before calling start again if setup was successful.

**Review by fortuna — CHANGES_REQUESTED** [review]
The flow looks good, but the code is violating the app/infrastructure boundaries. Let's push the app logic into the app code.

File: src/electron/index.ts [hunk 20]
```diff
@@ -438,13 +443,34 @@ function main() {
...
 
   // Disconnects from the current server, if any.
   promiseIpc.on('stop-proxying', stopVpn);
 
+  // Install backend services (for Linux only)
+  promiseIpc.on('install-outline-services', () => {
+    console.assert(isLinux, 'outline services can only be installed on Linux');
+    console.log('installing outline routing daemon...');
+    return new Promise<boolean>((resolve, reject) => {
+      sudo.exec(getServiceStartCommand(), {name: 'Outline'}, sudoError => {
```
[the remark this answers is not in the document]
Comment (jyyi1) [reply src/electron/index.ts]: Added a static `installRoutingServices` method in `RoutingDaemon` class.

File: src/electron/index.ts [hunk 21]
```diff
@@ -447,6 +450,9 @@ function main() {
   // Disconnects from the current server, if any.
   promiseIpc.on('stop-proxying', stopVpn);
 
+  // Install backend services (for Linux only)
+  promiseIpc.on('install-outline-services', RoutingDaemon.installRoutingServices);
```
Comment (fortuna) [inline src/electron/index.ts:454]: Can you use `ipcRenderer.invoke/handle` instead of `promiseIpc`?
https://www.electronjs.org/docs/latest/api/ipc-renderer#ipcrendererinvokechannel-args

I think promiseIpc forces us to have nodeIntegration, which I'd like to remove.

File: src/electron/routing_service.ts [hunk 22]
```diff
@@ -234,4 +217,22 @@ export class RoutingDaemon {
   public set onNetworkChange(newListener: ((status: TunnelStatus) => void) | undefined) {
     this.networkChangeListener = newListener;
   }
+
+  public static installRoutingServices(): Promise<boolean> {
```
Comment (fortuna) [inline src/electron/routing_service.ts:221]: Make this a standalone function to make it clearer that there's no need to access private members of `RoutingDemon`

File: src/electron/routing_service.ts [hunk 23]
```diff
@@ -234,4 +217,22 @@ export class RoutingDaemon {
...
+    console.assert(isLinux, 'outline services can only be installed on Linux');
+    console.log('installing outline routing daemon...');
+    return new Promise<boolean>((resolve, reject) => {
+      sudo.exec(getServiceStartCommand(), {name: 'Outline'}, sudoError => {
```
Comment (fortuna) [inline src/electron/routing_service.ts:225]: Pull the service command logic into this file.

File: src/electron/index.ts (hunk 21 above)
Comment (jyyi1) [reply src/electron/index.ts:454]: Good idea. I was also thinking of that. Maybe previously our electron version is too old to use `ipcRenderer.invoke`.

Comment (jyyi1) [reply src/electron/index.ts]: I used `ipcRenderer.invoke` for `install-outline-services` IPC call. We can migrate other IPC calls as well (like `start-proxy`), let me do it in another PR.

**Review by fortuna — APPROVED** [review]

File: src/www/app/tunnel.ts [hunk 24]
```diff
@@ -42,4 +42,15 @@ export interface Tunnel {
 
   // Sets a listener, to be called when the tunnel status changes.
   onStatusChange(listener: (status: TunnelStatus) => void): void;
+
+  /**
+   * Get a value indicating whether this tunnel is able to install required services at runtime.
+   */
+  readonly canInstallServices: boolean;
```
Comment (fortuna) [inline src/www/app/tunnel.ts:49]: This method is not needed. The code that throws the configuration error that triggers the installation only runs on the platforms that support installation.
Let's remove this method and always trigger the install flow on `SystemConfigurationException`

File: src/www/model/server.ts [hunk 25]
```diff
@@ -43,12 +43,18 @@ export interface Server {
 
   // Checks whether the server is reachable.
   checkReachable(): Promise<boolean>;
+
+  // Checks whether we can fix the underlying outline services for this server.
+  canFixServices(): Promise<boolean>;
+
+  // Try to fix the underlying outline services for this server.
+  tryFixServices(): Promise<void>;
```
Comment (fortuna) [inline src/www/model/server.ts:51]: Let's call it `installService` or something like `{configure|setup}Vpn`.
No `try` in the method name.

Also, the scope for this is not really a Server.
The service is shared.

I think we need to think more about how we may want to design this, but for now:
- add an install/configure/setup method to OutlineServerRepository. That's the right scope, and it doesn't have to be in the model, as it's mostly an application-specific concern.
- Add a corresponding method to the Tunnel, which gets called by the repo, and provides the actual implementation.

**Review by fortuna — CHANGES_REQUESTED** [review]

File: src/www/model/server.ts (hunk 25 above)
Comment (fortuna) [reply src/www/model/server.ts:51]: BTW, Android has the concept of "preparing" the VPN before using it. We may want to model it in a similar way as Electron in the future: https://developer.android.com/guide/topics/connectivity/vpn

File: src/www/app/app.ts [hunk 26]
```diff
@@ -367,11 +348,43 @@ export class App {
...
+          await this.installOutlineServices(server);
+          return;
+        }
+      }
+      this.showLocalizedError(e);
+    }
+  }
+
+  private async confirmToInstallOutlineServices(server: Server): Promise<boolean> {
+    if (!(await server.canFixServices())) {
```
[the remark this answers is not in the document]
Comment (jyyi1) [reply src/www/app/app.ts:366]: That's right.

File: src/www/model/server.ts (hunk 25 above)
Comment (jyyi1) [reply src/www/model/server.ts:51]: 👍

Comment (fortuna) [reply src/www/model/server.ts:51]: Sounds good

Comment (jyyi1) [reply src/www/model/server.ts]: I introduced a new `VpnInstaller` interface to do the work. So it decouples with `ServerRepository` or `Tunnel`.

File: src/electron/util.ts [hunk 27]
```diff
@@ -19,47 +19,35 @@ import * as os from 'os';
...
-  } else {
-    throw new Error('unsupported os');
-  }
+export function pathToEmbeddedBinary(toolname: string, filename: string) {
+  return path.join(unpackedAppPath(), 'third_party', toolname, os.platform(), filename + (isWindows ? '.exe' : ''));
 }
 
 // On some distributions, root is not allowed access the AppImage folder: copy the files to /tmp.
-function copyServiceFilesToTempFolder() {
+export function copyServiceFilesToTempFolder(sourcePathRelativeToApp: string, filenames: string[]) {
```
[the remark this answers is not in the document]
Comment (jyyi1) [reply src/electron/util.ts:44]: Because `sudo` cannot execute the commands in the AppImage's mounted folder. We can only read/execute the files using a regular user account (the account who starts `Outline.AppImage`) due to security concerns. Therefore we have to copy these files to a `/tmp` folder and execute them using `sudo`.

Here is a discussion: https://github.com/AppImage/AppImageKit/issues/146.

[the remark this answers is not in the document]
Comment (fortuna) [reply src/electron/util.ts:44]: Good to know. Perhaps add that link to the comment.

File: src/www/app/electron_main.ts [hunk 28]
```diff
@@ -73,6 +76,18 @@ class ElectronUpdater extends AbstractUpdater {
   }
 }
 
+class DesktopVpnInstaller implements VpnInstaller {
```
Comment (fortuna) [inline src/www/app/electron_main.ts:79]: Rename to ElectronVpnInstaller, as it doesn't apply to macOS.

File: src/www/app/vpn_installer.ts [hunk 29]
```diff
@@ -0,0 +1,32 @@
...
+// limitations under the License.
+
+/**
+ * Helper class to install VPN services to the OS.
+ */
+export interface VpnInstaller {
+  /**
+   * Setup the underlying outline VPN services.
+   */
+  setupVpn(): Promise<void>;
```
Comment (fortuna) [inline src/www/app/vpn_installer.ts:22]: Please align the wording.

If this is called `VpnInstaller`, then the mehod should be `installVpn()`.

Or maybe we can call it `VpnService` and just have a `setUp/install()` method?

I think we could make it part of the RoutingService if we changed its scope, but that would be a bigger change.

File: src/www/app/app.ts [hunk 30]
```diff
@@ -367,11 +350,33 @@ export class App {
...
+        if (await this.showConfirmationDialog(this.localize('outline-services-installation-confirmation'))) {
+          await this.installOutlineServices();
+          return;
+        }
+      }
+      this.showLocalizedError(e);
+    }
+  }
+
+  private async installOutlineServices(): Promise<void> {
```
Comment (fortuna) [inline src/www/app/app.ts:367]: This could be renamed to `installVpnService`, to align the names

File: src/www/app/electron_main.ts [hunk 31]
```diff
@@ -124,10 +133,7 @@ main({
...
     );
   },
-  getUpdater: () => {
-    return new ElectronUpdater();
-  },
-  quitApplication: () => {
-    ipcRenderer.send('quit-app');
-  },
+  getUpdater: () => new ElectronUpdater(),
+  getInstaller: () => new DesktopVpnInstaller(),
```
Comment (fortuna) [inline src/www/app/electron_main.ts:137]: Clarify:
```suggestion
  getVpnServiceInstaller: () => new DesktopVpnInstaller(),
```

File: src/electron/routing_service.ts [hunk 32]
```diff
@@ -235,3 +219,47 @@ export class RoutingDaemon {
...
+  if (isWindows) {
+    // Locating the script is tricky: when packaged, this basically boils down to:
+    //   c:\program files\Outline\
+    // but during development:
+    //   build/windows
+    //
+    // Surrounding quotes important, consider "c:\program files"!
+    return `"${path.join(getAppPath(), WINDOWS_INSTALLER_FILENAME)}"`;
+  } else if (isLinux) {
+    const tmpFolder = copyServiceFilesToTempFolder(OUTLINE_PROXY_CONTROLLER_PATH, [
```
[the remark this answers is not in the document]
Comment (jyyi1) [reply src/electron/routing_service.ts]: Refactored and added the comments to the file.

File: src/www/app/cordova_main.ts [hunk 33]
```diff
@@ -164,6 +165,10 @@ class CordovaPlatform implements OutlinePlatform {
     return new AbstractUpdater();
   }
 
+  getVpnServiceInstaller(): VpnInstaller {
+    return new NoOpVpnInstaller();
```
Comment (fortuna) [inline src/www/app/cordova_main.ts:169]: This could be a place to request for VPN permission and install the VPN profile on mobile in the future. I'm not sure we do the "heads up" before the permission prompt currently.

**Review by fortuna — APPROVED** [review]
Looks great! Thanks for fixing this
