### PR TITLE
🚸 fix(ui): navigation menu should be scrollable when window is too small

### LINKED ISSUE #1116: Cannot Outline client navigation menu if the windows is too short
**Describe the bug**
When the window is too short (or hold your phone horizontally), the left navigation menu is clipped, and cannot be scrolled down. So user will not be able to see all items.

**To Reproduce**
Make the height of the window shorter than the navigation menu.

**Expected behavior**
User can still view all navigation menu items by scrolling up and down.

**Screenshots**
N/A

**Client System (please complete the following information):**
All platforms.

**Submit Feedback**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jyyi1**
In this change set, I updated the navigation menu style to be vertically scrollable when the window is too small. The official way is to wrap a `<div>` element around: https://github.com/PolymerElements/app-layout/tree/master/app-drawer .

Fixes #1116 .

### CODE REVIEW

File: src/www/ui_components/app-root.js [hunk 1]
```diff
@@ -298,49 +298,51 @@ export class AppRoot extends mixinBehaviors
         <poop-with-flies-dot-gif/>
       -->
 
-      <div id="logo-nav">
-        <img src\$="[[rootPath]]assets/logo-nav.png" alt="logo" id="logo">
+      <div style="height: 100%; overflow-y: auto;">
```
Comment (daniellacosse) [inline src/www/ui_components/app-root.js:301]: You mind we add this into a css selector, rather than as a `style` property? they can be hard to override. Also does `overflow-y: scroll;` work?

**Comment by daniellacosse** [comment]
love the commitizen format btw

File: src/www/ui_components/app-root.js (hunk 1 above)
Comment (jyyi1) [reply src/www/ui_components/app-root.js:301]: `scroll` does not look good because it will always show a scrollbar even when the space is enough.

For the css selector, we can do that, but wanna be sure about the benefits, because this `<div>` does not have any semantic meanings, it is just used for the layout purpose.

Comment (daniellacosse) [reply src/www/ui_components/app-root.js:301]: True, `scroll` is a lot more obnoxious on windows.

You wouldn't be changing the `div` tag, just add a class to write the style against. It will remain non-semantic

Comment (jyyi1) [reply src/www/ui_components/app-root.js:301]: Yup, that's what I mean, since its only purpose is "layout", an inline style would make more sense to me to elaborate what this `<div>` is used for. If we use a css class, developers would need to navigate back and forth to understand why we have a `<div>` here.

Comment (jyyi1) [reply src/www/ui_components/app-root.js:301]: I just figured out another way, which is to name the css class as `.scrollable-drawer-root`, which can service both purposes (semantic in HTML and flexible in CSS).

Comment (jyyi1) [reply src/www/ui_components/app-root.js]: Updated the code.

Regarding the comment above, any `!important` in the code is a bad smell. If we do have a requirement to override the styles, we should put them into the CSS. What I was talking about before is, do we really need to override the layout styles? One of the use case I can think of is, using different layouts for different screen sizes.

Comment (daniellacosse) [reply src/www/ui_components/app-root.js]: I think it's just one of those habit things. Junior devs (or in our case, other contributors) see inline styles and start copying that without thinking. Eventually it grows into a problem. We generally will need to override attributes, it's in the name (_Cascading_ Style Sheets) and it's kind of hubris to think we can predict which ones we'll have to override in the future. Who knows what features we'll be developing in 2022? Having a consistent approach to our CSS will serve us well.

I think the real real way to solve the problem that's irking you is to create a new web component primitive, specifically called `<scroll-viewer>`, but I'd argue that's overengineering, at this point

Comment (jyyi1) [reply src/www/ui_components/app-root.js]: 😃 vote for `<scroll-viewer>`, but not in this pr.

Comment (daniellacosse) [reply src/www/ui_components/app-root.js]: I believe the vision is to prefer to use material primitives where we can rather than rolling our own, so that's something to factor in as well

**Review by daniellacosse — APPROVED** [review]

**Review by fortuna — APPROVED** [review]
